print('Olá! Eu não te conheço, qual é o seu nome?')
nome = input('Qual é o seu nome? ')
print('Então seu nome é:', nome,'? Nome legal!')
print('Agora preciso saber quantos anos você tem...')
idade = input('Quantos anos você tem? ')
print('Você tem', idade,' anos? Que legal! Eu também!')
gosto = input('Me fale algo que você gosta de fazer... ')
print('Você gosta de', gosto,'. Correto?')
pergunta = input('Correto? ')
print('Você disse', pergunta,'. Legal!')
print('Agora que nós já nos conhecemos', nome,', você pode voltar quando quiser!')
